### ISSUE TITLE
Upload the project report 1!

### ISSUE THREAD

**Issue by reddydavinci** [reddydavinci/leaveapplication#2]
Please do upload the project report 1

**Comment by ganesh123reddy** [comment]
[REPORT.pdf](https://github.com/reddydavinci/leaveapplication/files/2741764/REPORT.pdf)

**Comment by rahulmudam** [comment]
[REPORT.pdf](https://github.com/reddydavinci/leaveapplication/files/2741779/REPORT.pdf)
