### ISSUE TITLE
THE FRONT END SCHEMATIC PLEASE.

### ISSUE THREAD

**Issue by reddydavinci** [reddydavinci/leaveapplication#7]
Give the schematic of the login page and the interface of user for showing to the user and take feedback so that we could start working on that.

**Comment by ganesh123reddy** [comment]
[Overview.pdf](https://github.com/reddydavinci/leaveapplication/files/2798957/Overview.pdf)

**Comment by ganesh123reddy** [comment]
Uploaded the Schematics File
