### ISSUE TITLE
The Login and User Interfaces be ready!

### ISSUE THREAD

**Issue by reddydavinci** [reddydavinci/leaveapplication#9]
Give the login page and user interfaces.
Do not forget to upload in the front end section.

**Comment by reddydavinci** [comment]
Please look into the issue ASAP
@ganesh123reddy @rahulmudam

**Comment by reddydavinci** [comment]
The login page
The apply button be expanded
The different interfaces @rahulmudam @ganesh123reddy

**Comment by ganesh123reddy** [comment]
Changes Done
